#!/bin/bash

MODEL_DIR=${MODEL_DIR:-./models}

python3 -m cyberbully_detector \
  ./configs/midterm.config ./$MODEL_DIR/fold_0 \
  predict \
  $@ \
  --sup_model ./$MODEL_DIR/fold_1 ./$MODEL_DIR/fold_2
